name: Tests

on:
  pull_request: ~
  push: ~

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.dependencies || format('Symfony {0}', matrix.symfony) }}${{ (matrix.note && format(' ({0})', matrix.note)) || '' }}${{ (matrix.allow-failure && ' 🔕') || '' }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure || false }}
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony }}
      SYMFONY_DEPRECATIONS_HELPER: ${{ matrix.symfony-deprecations }}
      PARAM_DB_DRIVER: ${{ matrix.db-driver }}

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            php: '7.3'
            dependencies: lowest
          -
            php: '8.2'
            dependencies: highest
            symfony-deprecations: max[indirect]=5722
          -
            php: '7.3'
            symfony: '4.4.*'
          -
            php: '7.3'
            symfony: '4.4.*'
            note: sqlite
            db-driver: pdo_sqlite
          -
            php: '7.4'
            symfony: '5.4.*'
          # TODO remove as soon as Symfony >= 5.0 is required
          -
            php: '7.4'
            symfony: '5.4.*'
            note: contao-polyfill-symfony
            contao-polyfill-symfony: true
          -
            php: '8.0'
            symfony: '5.4.*'
          -
            php: '8.1'
            symfony: '5.4.*'
          -
            php: '8.1'
            symfony: '6.3.*'
            symfony-deprecations: max[indirect]=5722
          -
            php: '8.2'
            symfony: '6.4.*'
            stability: dev
            allow-failure: true

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysql, redis
          coverage: pcov
          ini-values: memory_limit=-1
          tools: flex
        env:
          fail-fast: true # interrupt on extension setup error

      # TODO remove as soon as Symfony >= 5.0 is required
      - name: require contao/polyfill-symfony
        if: matrix.contao-polyfill-symfony == true
        run: composer require --no-update --dev contao/polyfill-symfony

      - name: use dev dependencies
        if: matrix.stability == 'dev'
        run: composer config minimum-stability dev

      - name: install dependencies with Composer
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist

      - name: run PHPUnit
        run: vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml

      - name: upload code coverage data
        if: github.repository == 'craue/CraueFormFlowBundle'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: PHP ${{ matrix.php }} - ${{ matrix.dependencies || format('Symfony {0}', matrix.symfony) }}${{ (matrix.note && format(' ({0})', matrix.note)) || '' }}
        run: |
          unset SYMFONY_REQUIRE
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
